server:
  port: 8083

spring:
  cloud:
    stream:
      kafka:
        streams:
          binder:
            application-id: kafka-stream-demo
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.springframework.kafka.support.serializer.JsonSerde
              spring:
                json:
                  value:
                    default:
                      type: com.nsc.kafkastreamdemo.model.Event
          bindings:
            inputTable:
              consumer:
                materializedAs: all-songs
        binder:
          brokers: localhost:9092
      bindings:
        inputTable:
          destination: nscevent
          group: nsceventGroup
        eventOut:
          destination: nscevent